[Core.System]
Paths=../../../Engine/Content
Paths=%GAMEDIR%Content
Paths=../../../Engine/Plugins/ThirdParty/ImorBaker/Content
Paths=../../../Engine/Plugins/json2struct/Content
Paths=../../../Engine/Plugins/Experimental/FieldSystemPlugin/Content
Paths=../../../Client/Plugins/LGUI/LGUI/Content
Paths=../../../Engine/Plugins/PrefabSystem/Content
Paths=../../../Engine/Plugins/FX/Niagara/Content
Paths=../../../Client/Plugins/Kuro/KuroGameplay/Content
Paths=../../../Client/Plugins/Puerts/Puerts/Content
Paths=../../../Client/Plugins/Wwise/Content
Paths=../../../Engine/Plugins/Editor/GeometryMode/Content
Paths=../../../Engine/Plugins/MovieScene/SequencerScripting/Content
Paths=../../../Engine/Plugins/Experimental/PythonScriptPlugin/Content
Paths=../../../Client/Plugins/CrashSight/Content
Paths=../../../Engine/Plugins/ThirdParty/QuickEditor/Content
Paths=../../../Client/Plugins/Kuro/TASdkPlugin/Content
Paths=../../../Engine/Plugins/rdLODtools/Content
Paths=../../../Client/Plugins/AudioMaterialPlugin/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/DLSS/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/Streamline/Content
Paths=../../../Engine/Plugins/Runtime/HoudiniEngine/Content
Paths=../../../Client/Plugins/Kuro/KuroHotPatch/Content
Paths=../../../Client/Plugins/Kuro/KuroImer/Content
Paths=../../../Client/Plugins/Kuro/KuroAutomationTool/Content
Paths=../../../Engine/Plugins/FX/HoudiniNiagara/Content
Paths=../../../Client/Plugins/LogicDriverLite/Content
Paths=../../../Engine/Plugins/Runtime/AudioSynesthesia/Content
Paths=../../../Engine/Plugins/Experimental/ControlRig/Content
Paths=../../../Engine/Plugins/Media/MediaCompositing/Content
Paths=../../../Engine/Plugins/Runtime/Synthesis/Content
Paths=../../../Engine/Plugins/SequenceDialogue/Content
Paths=../../../Client/Plugins/Puerts/ReactUMG/Content
Paths=../../../Client/Plugins/genesis-ue-plugin/RenderExporter/Content
Paths=../../../Engine/Plugins/KuroiOSDelegate/Content
Paths=../../../Client/Plugins/Kuro/KuroGachaTools/Content
Paths=../../../Client/Plugins/Kuro/KuroPushSdk/Content
Paths=../../../Client/Plugins/SpinePlugin/Content
Paths=../../../Client/Plugins/TpSafe/Content
Paths=../../../Engine/Plugins/AssetChecker/Content
Paths=../../../Engine/Plugins/Editor/SpeedTreeImporter/Content
Paths=../../../Engine/Plugins/Experimental/ChaosClothEditor/Content
Paths=../../../Engine/Plugins/Experimental/ChaosNiagara/Content
Paths=../../../Engine/Plugins/Experimental/ChaosSolverPlugin/Content
Paths=../../../Engine/Plugins/MagicLeap/MagicLeapPassableWorld/Content
Paths=../../../Engine/Plugins/MagicLeap/MagicLeap/Content
Paths=../../../Engine/Plugins/MegascansPlugin/Content
Paths=../../../Client/Plugins/KuroTDM/Content
Paths=../../../Client/Plugins/MagtModule/Content
Paths=../../../Client/Plugins/ActionRoguelike/Metadata/PipelineCaches
Paths=../../../Client/Plugins/Kuro/KuroCloudGame/Content
Paths=../../../Engine/Plugins/Developer/PixelDebug/Content
Paths=../../../Engine/Plugins/PWPlugin/Content
Paths=../../../Engine/Plugins/BlueprintFileUtils/Content
Paths=../../../Client/Plugins/Kuro/WeLingPipeSDK/Content
Paths=../../../Engine/Plugins/Runtime/Intel/XeSS/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/NRD/Content
Paths=../../../Client/Plugins/ComfyTextures/Content
Paths=../../../Client/Plugins/Kuro/KuroPSOTools/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/Streamline_Old/Content
Paths=../../../Engine/Plugins/AFME/Content
Paths=../../../Engine/Plugins/Animation/ACLPlugin/Content
Paths=../../../Engine/Plugins/GSR/Content
TimeBetweenPurgingPendingKillObjects=60
MaxObjectsNotConsideredByGC=0
SizeOfPermanentObjectPool=0
launch=nogpucrashdebugging
launch=nothreadtimeout
launch=noailogging
launch=noverifygc
launch=noverifyex
launch=novsync
launch=high

[SystemSettings]
r.UsePerformanceProfiling=1   
r.MobileContentScaleFactor=1   
r.SecondaryScreenPercentage=100.11
r.SecondaryScreenPercentage.GameViewport=100.11
##RENDERING
r.Vsync=0
r.OneFrameThreadLag=1  
r.ViewDistanceScale=0.25
r.LODDistanceFactor=0.25
##FEATURE
r.DiffuseIndirect.Denoiser=0  
r.SSR.Quality=0
r.Tonemapper.GrainQuantization=0
r.MotionBlurQuality=0
r.DepthOfFieldQuality=0
r.BloomQuality=1 
r.MobileHDR=1
##KURO??
r.Kuro.OverallPerformancePriority.Aggressive=2
r.Kuro.ScenePerformancePriority.Aggressive=2 
r.Kuro.CombatPerformancePriority.Aggressive=2
r.Kuro.PerformancePriority=1 
##INSTANT CULLING
r.InstanceCulling.OcclusionCull=1  
r.InstanceCulling.BackfaceCull=1  
r.InstanceCulling.FrustumCull=1  
r.InstanceCulling.AllowInstanceOrderPreservation=0  
##CULLINGTUNING
r.AlsoUseSphereForFrustumCull=0  
r.AlsoUseSphereForOcclusionCull=0  
r.AlsoUseSphereForBackfaceCull=0
r.FrustumCullNumWordsPerTask=1  
##AMBIENTOCLUSSION
r.AOHistoryStabilityPass=0  
r.CacheHistoryStabilityPass=0
#r.FastVRam
r.FastVRam.SceneColor=1
r.FastVRam.SceneDepth=1
r.FastVRam.HZB=1
r.FastVRam.Tonemap=1
r.FastVRam.MotionBlur=1
r.FastVRam.DistanceFieldShadows=1
r.FastVRam.DistanceFieldTileIntersectionResources=1
r.FastVRam.ShadowCSM=1
r.FastVRam.GBufferA=1
r.FastVRam.GBufferB=1
r.FastVRam.GBufferC=1
r.FastVRam.GBufferD=1
r.FastVRam.GBufferE=1
r.FastVRam.GBufferVelocity=1
#SHADOW
r.LightFunctionQuality=0
r.ShadowQuality=0
r.Shadow.CSM.MaxCascades=1
r.Shadow.MaxResolution=512
r.Shadow.RadiusThreshold=0.06
r.Shadow.DistanceScale=0.6
r.Shadow.CSM.TransitionScale=0
r.Shadow.Grass.Enable=0
;#TEXTURE
r.TextureStreaming=1
r.Streaming.UseFixedPoolSize=1
r.Streaming.PoolSize=150
r.Streaming.MaxTempMemoryAllowed=20
r.Streaming.DefragDynamicBounds=1
r.Streaming.LimitPoolSizeToVRAM=1
##PERFORMANCE OPTIMIZE
r.MaxAnisotropy=6
r.Streaming.AmortizeCPUToGPUCopy=1
r.Streaming.PoolSizeBoost=0
r.Streaming.PassCPUtoGPU=1 
r.Streaming.FullyLoadUsedTextures=0
r.AllowGlobalClipPlane=0
r.DrawRectangleOptimization=1  
r.DownsampledOcclusionQueries=1  
##OPTIONAL
r.Streaming.MipBias=2
r.Streaming.HLODStrategy=1
r.StreamingLevelDistance=3000
#DETAIL MODE
r.DetailMode=1
#FOLIAGE
foliage.DensityScale=0.25
grass.DensityScale=0.2
r.GrassLODBias=2
r.Grass.CullDistanceScale=0.2
r.Grass.DiscardDataOnLoad=1
##DISTANCE
r.MaxDrawDistance=5000
r.OcclusionCulling=1
r.FoliageInteraction=0
r.FoliageForceLOD=2
r.FoliageVertexFactory=1
foliage.ShadowDistanceScale=0
foliage.UseVertexShaderLODs=1
##SHADOW
grass.DisableDynamicShadows=1
grass.DisableDynamicMovement=1 

[/Script/Engine.Engine]
bSmoothFrameRate=False
bUseFixedFrameRate=False
t.MaxFPS=60

[/Script/Engine.GameEngine]
bUseLessCPUInBackground=True

[Engine.Streaming]
RenderPriority=1

[UnrealEd.EditorEngine]
GodMode=1

[AnimationCompression]
CompressCommandletVersion=1
ForceRecompression=False
TranslationCompressionFormat=7
RotationCompressionFormat=7
AlternativeCompressionThreshold=1.0

[/Script/Engine.AnimationSettings]
bTickAnimationOnSkeletalMeshInit=False
bTickAnimationOnSkeletalMeshInit=False
bSimulateAnimationOnGameThread=False
bSimulateAnimationOnGameThread=False
bUseDynamicRefSkeletons=False
bDisableAnimationOnGameThread=True
bAllowMultiThreadedAnimationUpdateOnGameThread=False

[SystemSettingsEditor]
r.Mobile.DisableVertexFog=1
r.Mobile.AllowMovableLightShadows=0
r.Mobile.EnableStaticAndCSMShadowReceivers=0
r.Mobile.AllowDistanceFieldShadows=0
r.Mobile.EnableMovableSpotlights=0

[/Script/Engine.GarbageCollectionSettings]
gc.TimeBetweenPurgingPendingKillObjects=60
gc.NumRetriesBeforeForcingGC=1
gc.AllowParallelGC=False

[SystemSettings.ShaderPipelineCache]
SaveAfterPSOsLoaded=1
UseShaderPipelineCache=1
GameFileMaskEnabled=1
BatchSize=16
PrecompileBatchSize=16

[SystemSettings.FX]
t.MaxFPS=60
bAllowHiddenAnimationObject=False
bDisableSkeletalAnimationUpdate=True
bForceDisableProcessing=True
bDisableParticleCulling=True
MaxParticleResize=0.1
MaxParticleResizeWarn=0.1

[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
PackageName=com.kurogames.wutheringwaves.global
bUseAudioStreamCaching=False
bUseTextureStreamCaching=False
CompressionQualityModifier=1
CompressionOverrides=(MaxNumRandomBranches=0,SoundCueQualityIndex=0)

[Culling]
LODCullMapIndex=8
LODMipBias=-1000
Handle.StacksToRemove=-1

[TextureStreaming]
PoolSize=430
PoolSizeVRAMPercentage=80
PoolSizeVRAMHeapSize=20
MemoryMargin=512
HysteresisLimit=100
DropMipLevelsLimit=16
StopIncreasingLimit=12
StopStreamingLimit=7
MinFudgeFactor=0.2
FudgeFactorIncreaseRateOfChange=0.3
FudgeFactorDecreaseRateOfChange=-0.7
MinRequestedMipsToConsider=11
MinTimeToGuaranteeMinMipCount=0
MaxTimeToGuaranteeMinMipCount=0
UseTextureFileCache=true
MaxTextureMipCount=11
bSavedTextureCompiling=true
bUseBackgroundLevelStreaming=true
bUseLessCPUInBackground=true
bUseLessGPUInBackground=true

[CrashReportClient]
bSendUnattendedBugReports=false
bAgreeToCrashUpload=false
bImplicitSend=false
bAllowToBeContacted=false
bSendLogFile=false
bSendDumpLog=false
bSendReport=false

[VertexCompress]
r.DynamicMesh.VertexCompressEnabled=1
r.GlobalMesh.VertexCompressEnabled=1
r.HDRMesh.VertexCompressEnabled=1
r.SDRMesh.VertexCompressEnabled=1
r.VegetationMesh.VertexCompressEnabled=1

[DevOptions.Shaders]
NumUnusedShaderCompilingThreads=8
NumUnusedShaderCompilingThreadsDuringGame=8
PercentageUnusedShaderCompilingThreads=0
ShaderCompilerCoreCountThreshold=8
ThreadedShaderCompileThreshold=8
CookerMemoryUsedInGB=4
MemoryToLeaveForTheOSInGB=3
MemoryUsedPerSCWProcessInGB=4
WorkerProcessPriorityHigh=1
WorkerProcessPriority=1
CoresProcessPriority=8
ThreadsProcessPriority=8
SetPriority=High
SetAffinity=All
bUseVirtualCores=True

[DerivedDataBackendGraph]
UnusedFileAge=0
MaxFileChecksPerSec=1
PurgeableAssests=1
DeletedUnused=1

[StudioTelemetry.Log]
EngineVersion=4.27.2
Lib=4.27.2
Lib2=5.5.1
FileName=null
Dump=null

[Startup]
autoexeccfg=1
highprio=1
digitalmk=UCDni03Gp5Z2ce3TboBosTgg
